### ISSUE TITLE
Which is upstream

### ISSUE THREAD

**Issue by PanderMusubi** [richard-better/pushbullet.py#181]
@rharder @rbrcsk What is the proper upstream repo and if possible, please merge the work from https://github.com/rharder/asyncpushbullet into https://github.com/rbrcsk/pushbullet.py/

https://pypi.org/project/asyncpushbullet/ lists the first repo mentioned above as the homepage but this upstream repo has more recent activity.

**Comment by rharder** [comment]
Thanks for the question. My it’s been a while since I forked that. I think I took the original and then added all the asyncio code, making changes to the original along the way. 

So I’m not really sure what’s the appropriate way to handle that. It doesn’t bother me which way we work it out. 

Does it cause trouble the way It’s communicated (or not communicated) now?

Rob

**Comment by PanderMusubi** [comment]
Thanks for your reply. I don't think it give troubles at the moment. Clould you rebase your fork and make a PR for merging upstream? Hope all comes together in that way. PS I'm using your fork, thanks for your work on that.

**Comment by rbrcsk** [comment]
I'm happy to deprecate and archive this repo in favour of @rharder's version. I sadly don't have the capacity to work on this, especially since Pushbullet does not work on iOS. 

Alternatively if you'd prefer, I could hand over ownership of this repo as well. Let me know what you think!

**Comment by rharder** [comment]
LOL!  I also don’t work on the repo anymore because they dropped iOS support!  Funny.

-Rob

**Comment by rbrcsk** [comment]
Looks like the conclusion is that neither of the packages are actively supported, or "upstream". I've added a deprecation notice, and I'm archiving this repo to avoid further confusion.
